
TYPE
	EasyUaConnGetStatusInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL;
		Executing : {REDUND_UNREPLICABLE} BOOL;
		ParametersValid : {REDUND_UNREPLICABLE} BOOL;
		ServerEndpointUrl : {REDUND_UNREPLICABLE} STRING[255];
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		ConnectionStatus : {REDUND_UNREPLICABLE} UAConnectionStatus;
		ServerState : {REDUND_UNREPLICABLE} UAServerState;
		ServiceLevel : {REDUND_UNREPLICABLE} BYTE;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_ConnectionGetStatus_0 : {REDUND_UNREPLICABLE} UA_ConnectionGetStatus;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaReadInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL;
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF STRING[MAX_LENGTH_VARIABLE];
		TimeStamps : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DATE_AND_TIME;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_ReadList_0 : {REDUND_UNREPLICABLE} UA_ReadList;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaReadListInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF STRING[MAX_LENGTH_VARIABLE];
		TimeStamps : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DATE_AND_TIME;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_ReadList_0 : {REDUND_UNREPLICABLE} UA_ReadList;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaReadBulkInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} UDINT;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		NodeIDsAdr : {REDUND_UNREPLICABLE} UDINT;
		NodeIDsLen : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		BrUa_ReadBulk_0 : {REDUND_UNREPLICABLE} BrUa_ReadBulk;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaWriteInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF STRING[MAX_LENGTH_VARIABLE];
		Idx : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_WriteList_0 : {REDUND_UNREPLICABLE} UA_WriteList;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaWriteListInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF STRING[MAX_LENGTH_VARIABLE];
		Idx : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_WriteList_0 : {REDUND_UNREPLICABLE} UA_WriteList;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaWriteBulkInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Variables : {REDUND_UNREPLICABLE} UDINT;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		NodeIDsAdr : {REDUND_UNREPLICABLE} UDINT;
		NodeIDsLen : {REDUND_UNREPLICABLE} UDINT;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		BrUa_WriteBulk_0 : {REDUND_UNREPLICABLE} BrUa_WriteBulk;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaSubscriptionInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		EnableOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		NodeStatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		MonitorStatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		PublishingInterval : {REDUND_UNREPLICABLE} TIME;
		SubscriptionListActive : {REDUND_UNREPLICABLE} BOOL;
		MonitoringParameter : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF UAMonitoringParameter;
		Variables : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF UAMonitoredVariables;
		ValuesChanged : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF BOOL;
		MinLostValueCount : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF UINT;
		ValueChangedOld : {REDUND_UNREPLICABLE} ARRAY[0..1]OF BOOL;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_SubscriptionCreate_0 : {REDUND_UNREPLICABLE} UA_SubscriptionCreate;
		UA_MonitoredItemAddList_0 : {REDUND_UNREPLICABLE} UA_MonitoredItemAddList;
		UA_MonitoredItemRemoveList_0 : {REDUND_UNREPLICABLE} UA_MonitoredItemRemoveList;
		UA_SubscriptionDelete_0 : {REDUND_UNREPLICABLE} UA_SubscriptionDelete;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaSubsListInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		EnableOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		NodeStatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_NODELIST]OF DWORD;
		MonitorStatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF DWORD;
		NodeIDCount : {REDUND_UNREPLICABLE} UINT;
		Idx : {REDUND_UNREPLICABLE} UDINT;
		PublishingInterval : {REDUND_UNREPLICABLE} TIME;
		SubscriptionListActive : {REDUND_UNREPLICABLE} BOOL;
		MonitoringParameter : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_MONITORLIST]OF UAMonitoringParameter;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_NodeGetHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeGetHandleList;
		UA_SubscriptionCreate_0 : {REDUND_UNREPLICABLE} UA_SubscriptionCreate;
		UA_MonitoredItemAddList_0 : {REDUND_UNREPLICABLE} UA_MonitoredItemAddList;
		UA_MonitoredItemRemoveList_0 : {REDUND_UNREPLICABLE} UA_MonitoredItemRemoveList;
		UA_SubscriptionDelete_0 : {REDUND_UNREPLICABLE} UA_SubscriptionDelete;
		UA_NodeReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_NodeReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
	EasyUaMethodCallInternalType : {REDUND_UNREPLICABLE} 	STRUCT  (*Internal structure.*) (* *) (*#OMIT*)
		ExecuteOld : {REDUND_UNREPLICABLE} BOOL; 
		Executing : {REDUND_UNREPLICABLE} BOOL; 
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; 
		KeepConnection : {REDUND_UNREPLICABLE} BOOL;
		Step : {REDUND_UNREPLICABLE} UDINT;
		ConnectionHdl : {REDUND_UNREPLICABLE} DWORD;
		InputArguments : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_ARGUMENTS]OF BrUaMethodArgument;
		OutputArguments : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_ARGUMENTS]OF BrUaMethodArgument;
		StatusID : {REDUND_UNREPLICABLE} DWORD;
		StatusIDs : {REDUND_UNREPLICABLE} ARRAY[0..MAX_INDEX_METHOD]OF DWORD;
		MethodResult : {REDUND_UNREPLICABLE} DWORD;
		UA_Connect_0 : {REDUND_UNREPLICABLE} UA_Connect;
		UA_NamespaceGetIndexList_0 : {REDUND_UNREPLICABLE} UA_NamespaceGetIndexList;
		UA_MethodGetHandleList_0 : {REDUND_UNREPLICABLE} UA_MethodGetHandleList;
		UA_MethodCall_0 : {REDUND_UNREPLICABLE} UA_MethodCall;
		UA_MethodReleaseHandleList_0 : {REDUND_UNREPLICABLE} UA_MethodReleaseHandleList;
		UA_Disconnect_0 : {REDUND_UNREPLICABLE} UA_Disconnect;
	END_STRUCT;
END_TYPE
